services:
  clients-api:
    build: .
    container_name: tcc_clients
    command: uvicorn clients.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    volumes:
      - .:/app

  products-api:
    build: .
    container_name: tcc_products
    command: uvicorn products.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    volumes:
      - .:/app

  quotes-api:
    build: .
    container_name: tcc_quotes
    command: uvicorn quotes.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    volumes:
      - .:/app

  sales-api:
    build: .
    container_name: tcc_sales
    command: uvicorn sales.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    volumes:
      - .:/app
  
  nginx:
    image: nginx:latest
    container_name: tcc_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - clients-api
      - products-api
      - quotes-api
      - sales-api
